# Generated by Django 3.0.7 on 2020-12-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_business_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='user',
        ),
        migrations.AddField(
            model_name='business',
            name='users',
            field=models.ManyToManyField(to='business.BaseUser'),
        ),
    ]
