# Generated by Django 3.1.4 on 2020-12-22 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_auto_20201222_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('photo', models.ImageField(default='avatar.png', upload_to='uploads')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_categories', to='business.business')),
            ],
        ),
    ]
