# Generated by Django 3.1.4 on 2020-12-23 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('price', models.BigIntegerField()),
                ('stock', models.BigIntegerField()),
                ('photo', models.ImageField(default='avatar.png', upload_to='uploads')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_products', to='business.business')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='business.category')),
            ],
        ),
    ]
