# Generated by Django 3.1.4 on 2021-01-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessrole',
            name='business',
        ),
        migrations.RemoveField(
            model_name='businessrole',
            name='user',
        ),
        migrations.AddField(
            model_name='businessrole',
            name='business_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='businessrole',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
